version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000" # Porta para acessar o serviço
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data # Monta um volume persistente para salvar os dados no diretório raiz
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local