name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main # Modifique a branch caso necessário (realiza o deploy na branch main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o Node.js
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Ajuste para a versão necessária do Lambda
          cache: 'npm'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Build da aplicação
      - name: Build the application
        run: npm run build

      # 5. Compactar a aplicação para o deploy (conteúdo da pasta ./dist)
      - name: Create deployment package
        run: |
          cd dist
          zip -rq ../function.zip . # Compacta os arquivos do build na raiz
        shell: bash

      # 6. Instalar AWS CLI no ambiente de execução
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # 7. Configurar credenciais da AWS (usando os secrets do repositório)
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      # 8. Deploy da Lambda usando AWS CLI
      - name: Deploy Lambda to AWS
        run: |
          aws lambda create-function \
            --function-name saveGameInfo \
            --runtime nodejs22.x
            --zip-file fileb://function.zip \
            --region ${{ secrets.AWS_REGION }}